# Generated by Django 4.1.5 on 2023-02-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
