# Generated by Django 4.1.5 on 2023-02-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='unidades',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='numero_sku',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='unidades_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salida',
            name='unidades_out',
            field=models.IntegerField(),
        ),
    ]
