# Generated by Django 4.1.5 on 2023-02-16 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eboxApp', '0005_remove_recepcion_sku_in_remove_salida_sku_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=300)),
                ('numero_sku', models.IntegerField()),
                ('categoria', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_out', models.IntegerField()),
                ('orden_venta', models.IntegerField()),
                ('sku_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eboxApp.maestra')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contenedor', models.CharField(max_length=100)),
                ('unidades_in', models.IntegerField()),
                ('sku_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eboxApp.maestra')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eboxApp.maestra')),
            ],
        ),
    ]
