# Generated by Django 4.1.5 on 2023-02-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='orden_venta',
            field=models.CharField(max_length=100),
        ),
    ]
