# Generated by Django 4.1.5 on 2023-02-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0008_rename_sku_in_recepcion_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='unidades',
        ),
    ]
