# Generated by Django 4.1.5 on 2023-02-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0009_remove_inventario_sku_remove_inventario_unidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcion',
            old_name='sku',
            new_name='sku_in',
        ),
        migrations.RenameField(
            model_name='recepcion',
            old_name='unidades',
            new_name='unidades_in',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='sku',
            new_name='sku_out',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='unidades',
            new_name='unidades_out',
        ),
        migrations.AddField(
            model_name='inventario',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eboxApp.maestra'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tot_unidades',
            field=models.IntegerField(null=True),
        ),
    ]
