# Generated by Django 4.1.5 on 2023-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0010_rename_sku_recepcion_sku_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='tot_unidades',
            field=models.IntegerField(default=0),
        ),
    ]
