# Generated by Django 4.1.5 on 2023-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0011_alter_inventario_tot_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='tot_unidades',
            field=models.IntegerField(null=True),
        ),
    ]
