# Generated by Django 4.1.7 on 2023-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0012_alter_inventario_tot_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='fecha_despacho',
            field=models.DateField(null=True),
        ),
    ]
