# Generated by Django 4.1.7 on 2023-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0014_recepcion_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestra',
            name='numero_sku',
            field=models.CharField(max_length=300),
        ),
    ]
