# Generated by Django 4.1.7 on 2023-02-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0015_alter_maestra_numero_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='orden_compra',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
