# Generated by Django 4.1.7 on 2023-03-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0017_alter_salida_sku_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eboxApp.recepcion')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eboxApp.maestra')),
            ],
        ),
    ]
