# Generated by Django 4.1.7 on 2023-03-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0018_detallerecepcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleRecepcion',
        ),
    ]
