# Generated by Django 4.1.7 on 2023-03-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0020_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eboxApp.estados'),
        ),
    ]
