# Generated by Django 4.1.7 on 2023-03-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0021_salida_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='eboxApp.estados'),
        ),
    ]
