# Generated by Django 4.1.7 on 2023-03-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0022_alter_salida_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='unidades_disponibles',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='unidades_reservadas',
            field=models.IntegerField(null=True),
        ),
    ]
