# Generated by Django 4.1.7 on 2023-03-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0027_inventario_unidades_reservadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='unidades_reservadas',
            field=models.IntegerField(),
        ),
    ]
