# Generated by Django 4.1.7 on 2023-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0030_alter_salida_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='unidades_entregadas',
            field=models.IntegerField(default=0),
        ),
    ]
