# Generated by Django 4.1.7 on 2023-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboxApp', '0031_inventario_unidades_entregadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='unidades_preparadas',
            field=models.IntegerField(default=0),
        ),
    ]
